# Generated by Django 6.0.2 on 2026-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_article_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='best_for',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='verdict',
            field=models.TextField(blank=True),
        ),
    ]
